# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_title', models.CharField(max_length=200)),
                ('article_url', models.URLField(primary_key=True, serialize=False)),
                ('release_time_detected', models.IntegerField()),
                ('article_excerpt', models.CharField(max_length=300)),
                ('article_content', models.CharField(max_length=50000)),
                ('article_class', models.CharField(max_length=150)),
                ('page_urlcode', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-release_time_detected'],
            },
        ),
    ]
