# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(),
        ),
    ]
